name: Notificar a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "✅ Se ha hecho push a main en el repo ${{ github.repository }} 🚀" ntfy.sh/devops-itla
